config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users
  resources :reminders, except: :show
  mount Sidekiq::Web => '/sidekiq'

    post 'notifications/:id/complete'  => 'notifications#complete', as: :complete_notification
    post 'notifications/:id/update_snooze' => 'notifications#update_snooze', as: :update_snooze_notification
    get 'notifications/:id/snooze' => 'notifications#snooze', as: :snooze_notification

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "reminders#index"
end

app/models/reminder.rb
class Reminder < ApplicationRecord
    validates :title, presence: true
    validates :due_date, presence: true
    validate :due_date_cannot_be_in_the_past
    enum :repeat_frequency, { no_repeat:0, daily: 1, weekly: 2, monthly: 3, yearly: 4}, default: 0

    belongs_to :user
    has_many :notifications, dependent: :destroy

    scope :chronological, -> { order(due_date: :asc) }
    scope :non_repeatable, -> { where(repeat_frequency: 0) }
    scope :after, -> (date) { where("due_date > ?", date).chronological }
    scope :before, -> (date) { where("due_date < ?", date).chronological }

    def due_date_cannot_be_in_the_past
        if due_date.present? && due_date < DateTime.now
            errors.add(:due_date, 'can not be in the past')
        end
    end

    def repeatable?
        repeat_frequency != 'no_repeat'
    end

    def not_repeatable?
        !repeatable?
    end

end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reminder, only: %i[update edit destroy]

  # GET /reminders or /reminders.json
  # Purpose: Fetches and displays a list of reminders and notifications for the current user.
  # URL: GET /reminders
  # Request Format: HTML
  # Parameters: None
  # Response Format: HTML
  def index
    today = Date.current
    tomorrow = today + 1.day
    reminders = current_user.reminders.after(DateTime.now)
    @today_reminders = reminders.select { |r| r.due_date.to_date == today }
    @tomorrow_reminders = reminders.select { |r| r.due_date.to_date == tomorrow }
    @upcoming_reminders = reminders.reject { |r| [today, tomorrow].include?(r.due_date.to_date) }
    @missed_reminders = current_user.reminders.non_repeatable.before(DateTime.now)
    @notifications = current_user.notifications.overdue
  end

  # GET /reminders/new
  # Purpose: Displays a form to create a new reminder.
  # Request Format: HTML
  # Parameters: None
  # Response Format: HTML
  def new
    @reminder = Reminder.new(due_date: DateTime.now + 10.minutes)
    @reminder.user = current_user
  end

  # GET /reminders/:id/edit
  # Purpose: Displays a form to edit an existing reminder.
  # Request Format: HTML
  # Parameters:
  #   - :id (required) - The ID of the reminder to be edited.
  # Response Format: HTML
  def edit; end

  # POST /reminders
  # Purpose: Creates a new reminder based on the submitted form data.
  # URL: POST /reminders
  # Request Format: HTML
  # Parameters: reminder (required)
  # - Contains the reminder attributes (title, description, due_date, repeat_frequency).
  # Response Format: Turbo Stream
  def create
    @reminder = current_user.reminders.build(reminder_params)

    respond_to do |format|
      if @reminder.save
        ReminderJob.perform_async(@reminder.id, ReminderJob::SOURCE_CREATE)
        format.turbo_stream { flash.now[:notice] = "Reminder was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminders/:id
  # Purpose: Updates an existing reminder based on the submitted form data.
  #  - reconfigure the reminder if some changes in due_date or repeat_frequency
  #  - cancel the previously scheduled ReminderJob ( by setting reconfigured to true)
  #  - schedule a new ReminderJob 
  # URL: PATCH/PUT /reminders/:id
  # Request Format: HTML
  # Parameters:
  # - :id (required) - The ID of the reminder to be updated.
  # - reminder (required)
  #  - Contains the updated reminder attributes (title, description, due_date, repeat_frequency).
  # Response Format: Turbo Stream (if successful) or HTML (if there are errors)
  def update
    @reminder.assign_attributes(reminder_params)
    # track changes in the due_date and repeat_frequency fields.
    # mark it to cancel a previously scheduled ReminderJob
    @reminder.reconfigured = true if @reminder.due_date_changed? || @reminder.repeat_frequency_changed?
    @replace = !(@reminder.due_date_changed? || @reminder.repeat_frequency_changed?)
    respond_to do |format|
      if @reminder.save
        ReminderJob.perform_async(@reminder.id, ReminderJob::SOURCE_UPDATE)
        format.turbo_stream { flash.now[:notice] = "Reminder was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/:id
  # Purpose: Deletes an existing reminder.
  # Request Format: HTML
  # Parameters:
  # - :id (required) - The ID of the reminder to be deleted.
  # Response Format: Turbo Stream (if successful) or HTML (if there are errors)
  def destroy
    respond_to do |format|
      if @reminder.destroy
        format.turbo_stream { flash.now[:notice] = "Reminder was successfully deleted." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_reminder
    @reminder = Reminder.find(params[:id])
  rescue StandardError => e
    redirect_to reminders_path
  end

  # Only allow a list of trusted parameters through.
  def reminder_params
    params.require(:reminder).permit(:title, :description, :due_date, :repeat_frequency)
  end
end

app/helpers/reminders_helper.rb
module RemindersHelper
  # Returns the id of the div that a reminder should be put in
  # based on it's due_date.
  #
  # reminder - The reminder to find a div for
  #
  # Examples
  #
  #   target_div_id_for_reminder(reminder)
  #   # => 'today-reminders'
  #
  # Returns the string id of the div that the reminder should be added to.

  def target_div_id_for_reminder(reminder)
    return "today-reminders" if today?(reminder)
    return "tomorrow-reminders" if tomorrow?(reminder)
    "upcoming-reminders"
  end

  # Format the time to be a 24 hour time string
  def format_24_hour(time)
    time.strftime("%H:%M")
  end

  private

  def today?(reminder)
    Date.today == reminder.due_date.to_date
  end

  def tomorrow?(reminder)
    Date.tomorrow == reminder.due_date.to_date
  end
end

app/views/reminders/_form.html.erb
<%= form_with(model: reminder) do |form| %>
  <% if reminder.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>
      <ul>
        <% reminder.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title ,input_html: { autofocus: true } ,class:'form-control'%>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description ,class:'form-control'%>
  </div>
  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.datetime_local_field :due_date, :value => reminder.due_date.strftime('%Y-%m-%dT%H:%M') , class:'form-control', min: DateTime.now, step: 1 %>
  </div>
  <div >
    <div class="raw" data-controller="reminder" >
      <%= form.label "Repeat" %>
      <div data-reminder-target="repeatFrequency" >
        <%= form.select :repeat_frequency, Reminder.repeat_frequencies.keys, { selected: reminder.repeat_frequency }, { class: "form-control" } %>
      </div>
    </div>
  </div>
  <%= form.submit class:"btn btn-primary" %>
  <%= link_to "Cancel", reminders_path , data: { turbo_frame: "_top"}, class:"btn btn-secondary" %>
<% end %>

app/views/reminders/_notification.html.erb
<div id="<%= dom_id(notification, :notification) %>">
  <div class="card-body">
    <div class="list-group">
      <div class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
        <div class="d-flex">
          <div class="d-flex justify-content-center align-items-center">
            <i class="fa-solid fa-bell fa-shake fa-xl" style="color: orange;"></i>
          </div>
          <div class="ps-2 d-flex justify-content-center align-items-center">
            <div class="fs-3 fw-bold mb-0">
              <%= format_24_hour(notification.scheduled_at) %>
            </div>
            <div class="px-2">
              <%= notification.reminder.title %>
            </div>
          </div>
        </div>
        <small class="text-muted">
        </small>
        <% if notification.reminder.repeatable? %>
          <span class="badge bg-secondary rounded-pill">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-repeat" viewBox="0 0 16 16">
              <path d="M11 5.466V4H5a4 4 0 0 0-3.584 5.777.5.5 0 1 1-.896.446A5 5 0 0 1 5 3h6V1.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384l-2.36 1.966a.25.25 0 0 1-.41-.192Zm3.81.086a.5.5 0 0 1 .67.225A5 5 0 0 1 11 13H5v1.466a.25.25 0 0 1-.41.192l-2.36-1.966a.25.25 0 0 1 0-.384l2.36-1.966a.25.25 0 0 1 .41.192V12h6a4 4 0 0 0 3.585-5.777.5.5 0 0 1 .225-.67Z"/>
            </svg>
          </span>
        <% end %>
        <div class="d-flex align-items-center">
          <%= form_with url: complete_notification_path(notification), method: :post do |form| %>
            <%= form.submit "Complete", method: :post, data: { turbo_frame: "_top" }, authenticity_token: true, class: "btn btn-primary rounded-pill me-2" %>
          <% end %>
          <%= link_to "Snooze", snooze_notification_path(notification), data: { turbo_frame: "modal-frame" }, class: "btn btn-secondary rounded-pill" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reminders/_notification_list.html.erb
<% if user_signed_in? %>
  <%= turbo_stream_from "reminders-stream-#{current_user.id}" %>
  <div id="user-notifications" data-user-id=<%= current_user.id %>>
  </div>
  <div class="row">
    <div class="col-md-8">
      <div class="card mb-3">
        <div class="card-header">
          <h2 class="h6 mb-0">Notifications</h2>
        </div>
        <%= turbo_frame_tag "notifications_div" do %>
          <% notifications.each do |notification| %>
            <%= render partial: "reminders/notification", locals:{notification: notification} %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/reminders/_reminder.html.erb
<li class="list-group-item d-flex justify-content-between align-items-center backgrop" id="<%= dom_id reminder %>">
  <div class="d-flex justify-content-center align-items-center ">
    <h2>
      <%= format_24_hour(reminder.due_date)%>
    </h2>
    <div class="px-2 fs-5">
      <%= reminder.title %>
    </div>
    <% if reminder.repeatable? %>
      <span class="badge bg-secondary rounded-pill">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-repeat" viewBox="0 0 16 16">
          <path d="M11 5.466V4H5a4 4 0 0 0-3.584 5.777.5.5 0 1 1-.896.446A5 5 0 0 1 5 3h6V1.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384l-2.36 1.966a.25.25 0 0 1-.41-.192Zm3.81.086a.5.5 0 0 1 .67.225A5 5 0 0 1 11 13H5v1.466a.25.25 0 0 1-.41.192l-2.36-1.966a.25.25 0 0 1 0-.384l2.36-1.966a.25.25 0 0 1 .41.192V12h6a4 4 0 0 0 3.585-5.777.5.5 0 0 1 .225-.67Z"/>
        </svg>
      </span>
    <% end %>
  </div>
  <div class="btn-group" role="group" aria-label="Reminder actions">
    <%= button_to "Edit", edit_reminder_path(reminder), method: :get, class: "btn btn-outline-primary btn-sm", data: { turbo_frame: "modal-frame" } %>
    <%= button_to "Delete", reminder, method: :delete , class: "btn btn-outline-primary btn-sm", data: { turbo_frame: "_top" } %>
  </div>
</li>

app/views/reminders/create.turbo_stream.erb
  <%= turbo_stream.append(target_div_id_for_reminder(@reminder), partial: "reminders/reminder",
      locals: {reminder: @reminder}) %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

app/views/reminders/destroy.turbo_stream.erb
<%= turbo_stream.remove(dom_id(@reminder)) %>
<% @reminder.notifications.each do |notification| %>
  <%= turbo_stream.remove(dom_id(notification, :notification)) %>
<% end %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

app/views/reminders/edit.html.erb
<main class="container">
  <%= turbo_frame_tag "modal-frame" do %>
    <h1 class="h3 modal-header">
      Editing reminder
    </h1>
    <div class="modal-body">
      <%= render "form", reminder: @reminder %>
    </div>
  <% end %>
</main>

app/views/reminders/index.html.erb
<div class="container my-4">
  <%= render partial: "notification_list",
  locals:{notifications: @notifications} %>
  <div class="col-md-4">
    <%= link_to "New reminder", new_reminder_path,
          class: "btn btn-primary btn-lg btn-block",
          data:{turbo_frame: "modal-frame"}
        %>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h2 class="h6 mb-0">Reminder List</h2>
      <hr />
    </div>
  </div>
  <div class="row" id="reminders">
    <div class="col-md-4" >
      <div class="card shadow mb-4 " >
        <div class="card-header bg-primary text-white">
          <h2 class="h5 mb-0">Today</h2>
        </div>
        <ul class="list-group list-group-flush" id="today-reminders">
          <% if @today_reminders.present? %>
            <% @today_reminders.each do |reminder| %>
              <%= render partial: "reminder", locals: {reminder: reminder} %>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card shadow mb-4" >
        <div class="card-header bg-secondary text-white">
          <h2 class="h5 mb-0">Tomorrow</h2>
        </div>
        <ul class="list-group list-group-flush" id="tomorrow-reminders">
          <% if @tomorrow_reminders.present? %>
            <% @tomorrow_reminders.each do |reminder| %>
              <%= render partial: "reminder", locals: {reminder: reminder} %>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card shadow mb-4">
        <div class="card-header bg-info text-white">
          <h2 class="h5 mb-0">Upcoming</h2>
        </div>
        <ul class="list-group list-group-flush" id="upcoming-reminders">
          <% if @upcoming_reminders.present? %>
            <% @upcoming_reminders.each do |reminder| %>
              <%= render partial: "reminder", locals: {reminder: reminder} %>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card shadow mb-4">
        <div class="card-header bg-info text-white">
          <h2 class="h5 mb-0">Missed</h2>
        </div>
        <ul class="list-group list-group-flush" id="upcoming-reminders">
          <% if @missed_reminders.present? %>
            <% @missed_reminders.each do |reminder| %>
              <%= render partial: "reminder", locals: {reminder: reminder} %>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/reminders/new.html.erb
<main class="container">
  <%= turbo_frame_tag "modal-frame" do %>
    <h1 class="h3 modal-header">
      New reminder
    </h1>
    <div class="modal-body">
      <%= render "form", reminder: @reminder %>
    </div>
  <% end %>
</main>

app/views/reminders/show.html.erb
<%= render @reminder %>
<div>
  <%= link_to "Edit this reminder", edit_reminder_path(@reminder),data:{ turbo_frame: "modal-frame"} %> |
  <%# to break out of the turbo frame use _top %>
  <%= link_to "Back to reminders", reminders_path, data: { turbo_frame: "_top" } %>
  <%= button_to "Destroy this reminder", @reminder, method: :delete , data: { turbo_frame: "_top" } %>
</div>

app/views/reminders/update.turbo_stream.erb
<% if @replace == true %>
  <%= turbo_stream.replace(
    @reminder,
    partial: "reminders/reminder",
    locals: {reminder: @reminder})
    %>
  <%= turbo_stream.remove(dom_id(@reminder,:notification)) %>
<% else %>
  <%= turbo_stream.remove(dom_id(@reminder)) %>
  <%= turbo_stream.append(target_div_id_for_reminder(@reminder),
    partial: "reminders/reminder",
    locals: {reminder: @reminder})
  %>
<% end %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>