config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users
  resources :reminders, except: :show
  mount Sidekiq::Web => '/sidekiq'

    post 'notifications/:id/complete'  => 'notifications#complete', as: :complete_notification
    post 'notifications/:id/update_snooze' => 'notifications#update_snooze', as: :update_snooze_notification
    get 'notifications/:id/snooze' => 'notifications#snooze', as: :snooze_notification

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "reminders#index"
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :reminder
  belongs_to :user

  validates :scheduled_at, presence: true

  scope :completed, -> { where.not(completed_at: nil) }
  scope :pending, -> { where(completed_at: nil) }
  scope :overdue, -> { pending.where("scheduled_at <= ?", DateTime.now) }
  scope :upcoming, -> { pending.where("scheduled_at > ?", DateTime.now) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: %i[complete update_snooze snooze]

  # POST /notifications/:id/complete
  # Purpose: Marks a notification as completed and handles the associated reminder.
  # URL: POST /notifications/:id/complete
  # Request Format: turbo_stream
  # Parameters:
  #   - :id (required) - The ID of the notification to be completed.
  # Response Format: Turbo Stream (if successful) or HTML (if there are errors)
  def complete
    @reminder = @notification.reminder
    @destroy = false
    respond_to do |format|
      if @reminder.repeatable?
        # marke this notification as completed, because the reminder has frequency
        if @notification.update_attribute("completed_at", DateTime.now)
          # we need to delete the notification from the div only
          format.turbo_stream { flash.now[:notice] = "Reminder was successfully completed." }
        else
          format.json { render json: {message: "Reminder was successfully completed."}, status: :unprocessable_entity }
        end
      else
        # reminder does not have frequency, delete the whole reminder
        @reminder.destroy
        # we need to delete the notification from the div and the reminder from the list
        @destroy = true
        format.turbo_stream { flash.now[:notice] = "Reminder was successfully completed." }
      end
    end
  end

  # GET /notifications/:id/snooze
  # Purpose: Displays the snooze form for a notification.
  # URL: GET /notifications/:id/snooze
  # Request Format: HTML
  # Parameters:
  #   - :id (required) - The ID of the notification for which to display the snooze form.
  # Response Format: HTML
  def snooze
  end

  # POST /notifications/:id/update_snooze
  # Purpose: To updates the snooze duration for a notification.
  # URL: POST /notifications/:id/update_snooze
  # Request Format: HTML
  # Parameters:
  #   - :id (required) - The ID of the notification to be snoozed.
  #   - :minutes (required) - The new snooze duration in minutes.
  # Response Format: Turbo Stream (if successful) or HTML (if there are errors)
  def update_snooze
    @reminder = @notification.reminder

    respond_to do |format|
      if @notification.update(scheduled_at: new_schedule_date)
        SnoozeJob.perform_async(@notification.id)
        if @reminder.not_repeatable?
          # updating the reminder to be listed in today list.
          @reminder.update(due_date: new_schedule_date)
        end
        format.turbo_stream { flash.now[:notice] = "Reminder was successfully snoozed." }
      else
        format.html { render :snooze, status: :unprocessable_entity }
      end
    end
  end

  private

  def new_schedule_date
    DateTime.now + params[:minutes].to_i.minutes
  end

  def set_notification
    @notification = Notification.find_by(id: params[:id])
    render_not_found if @notification.nil?
  end

  def render_not_found
    respond_to do |format|
      format.html { render file: "#{Rails.public_path}/404.html", status: :not_found, layout: false }
      format.json { render json: {error: "Notification not found"}, status: :not_found }
    end
  end
end

app/views/notifications/_snooze_form.html.erb
<% if notification.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(notification.errors.count, "error") %> prohibited this reminder from being saved:</h2>
    <ul>
      <% notification.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_tag(update_snooze_notification_path(notification), method: :post) do %>
  <%= hidden_field_tag :minutes, 5 %>
  <%= button_tag '5 minutes', class: 'form-control' %>
<% end %>
<%= form_tag(update_snooze_notification_path(notification), method: :post) do %>
  <%= hidden_field_tag :minutes, 10 %>
  <%= button_tag '10 minutes', class: 'form-control' %>
<% end %>
<%= form_tag(update_snooze_notification_path(notification), method: :post) do %>
  <%= hidden_field_tag :minutes, 30 %>
  <%= button_tag '30 minutes', class: 'form-control' %>
<% end %>
<%= form_tag(update_snooze_notification_path(notification), method: :post) do %>
  <%= hidden_field_tag :minutes, 45 %>
  <%= button_tag '45 minutes', class: 'form-control' %>
<% end %>
<%= form_tag(update_snooze_notification_path(notification), method: :post) do %>
  <%= hidden_field_tag :minutes, 60 %>
  <%= button_tag '1 hour', class: 'form-control' %>
<% end %>

app/views/notifications/complete.turbo_stream.erb
<%=turbo_stream.remove(dom_id(@notification, :notification))%>
<% if @destroy == true %>
  <%= turbo_stream.remove(@reminder)%>
<% end %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

app/views/notifications/snooze.html.erb
<main class="container">
  <%= turbo_frame_tag "modal-frame" do %>
    <h1 class="modal-header">
      Snooze for
    </h1>
    <div class="modal-body">
      <%= render "snooze_form", notification: @notification %>
    </div>
  <% end %>
</main>

app/views/notifications/update_snooze.turbo_stream.erb
<%# remove from notifications_div %>
<%= turbo_stream.remove(dom_id(@notification,:notification)) %>
<%# remove if already exists in reminders list [replace does not cover one case where the reminder does not exists in the list]%>
<%= turbo_stream.remove(@reminder)  %>
<%# add the new one to the list %>
<%= turbo_stream.append(target_div_id_for_reminder(@reminder
), partial: "reminders/reminder",
      locals: {reminder: @reminder
}) %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>