config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users
  resources :reminders, except: :show
  mount Sidekiq::Web => '/sidekiq'

    post 'notifications/:id/complete'  => 'notifications#complete', as: :complete_notification
    post 'notifications/:id/update_snooze' => 'notifications#update_snooze', as: :update_snooze_notification
    get 'notifications/:id/snooze' => 'notifications#snooze', as: :snooze_notification

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "reminders#index"
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, message| %>
  <div
    data-controller="removals"
    data-action="animationend->removals#remove"
    class="alert <%= flash_class(key) %> alert-dismissible fade
    show text-center" role="alert"
    style="animation: appear-then-fade 4s both;">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to "Reminders", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%= link_to "Today", reminders_path, class: "nav-item nav-link" %>
        <%= link_to "Tomorrow", reminders_path, class: "nav-item nav-link" %>
        <%= link_to "Upcoming", reminders_path, class: "nav-item nav-link" %>
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <%= link_to current_user.email, edit_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-item nav-link" %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Login", new_user_session_path, class: "nav-item nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsReminder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body >
    <div class=" w-100 h-100 canvas">
      <div class="circles"></div>
    </div>
    <div class="w-100 h-100">
      <div class="container-fluid ">
        <div class="row">
          <%= render partial: "layouts/nav" %>
        </div>
        <div class="row">
          <div id="flash" class="flash" style="min-height: 58px;">
            <%= render "layouts/flash" %>
          </div>
        </div>
        <div class="container">
          <%= yield %>
          <div
            class="modal"
            tabindex="-1"
            data-controller="turbomodal"
            data-action="turbo:frame-load->turbomodal#open turbo:submit-end->turbomodal#close"
            >
            <div class="modal-dialog">
              <div class="modal-content">
                <%= turbo_frame_tag "modal-frame" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>